### YamlMime:ManagedReference
items:
- uid: Funique.UI.ClientUIConfiguration
  commentId: T:Funique.UI.ClientUIConfiguration
  id: ClientUIConfiguration
  parent: Funique.UI
  children:
  - Funique.UI.ClientUIConfiguration.PlayListMenu
  - Funique.UI.ClientUIConfiguration.ShortcutClose
  - Funique.UI.ClientUIConfiguration.ShortcutUI
  - Funique.UI.ClientUIConfiguration.ShowHomeMenu
  - Funique.UI.ClientUIConfiguration.ShowTimeline
  - Funique.UI.ClientUIConfiguration.ShowToolbarIcon
  - Funique.UI.ClientUIConfiguration.ZoomSlider
  langs:
  - csharp
  - vb
  name: ClientUIConfiguration
  nameWithType: ClientUIConfiguration
  fullName: Funique.UI.ClientUIConfiguration
  type: Struct
  source:
    remote:
      path: Structure/ClientUIConfiguration.cs
      branch: v1.0
      repo: https://github.com/Funique2022/funique_ui.git
    id: ClientUIConfiguration
    path: ../../../project_unity_development/Assets/FuniquePlugin/UI/Structure/ClientUIConfiguration.cs
    startLine: 11
  assemblies:
  - Funique.UI
  namespace: Funique.UI
  summary: "\nThe client side cinema player binding user interface data structure <br />\n------------------------------------------------ <br />\n客戶端綁定 播放器介面 的 資料結構\n"
  example: []
  syntax:
    content: >-
      [Serializable]

      public struct ClientUIConfiguration
    content.vb: >-
      <Serializable>

      Public Structure ClientUIConfiguration
  inheritedMembers:
  - System.ValueType.Equals(System.Object)
  - System.ValueType.GetHashCode
  - System.ValueType.ToString
  attributes:
  - type: System.SerializableAttribute
    ctor: System.SerializableAttribute.#ctor
    arguments: []
  modifiers.csharp:
  - public
  - struct
  modifiers.vb:
  - Public
  - Structure
- uid: Funique.UI.ClientUIConfiguration.ShowTimeline
  commentId: F:Funique.UI.ClientUIConfiguration.ShowTimeline
  id: ShowTimeline
  parent: Funique.UI.ClientUIConfiguration
  langs:
  - csharp
  - vb
  name: ShowTimeline
  nameWithType: ClientUIConfiguration.ShowTimeline
  fullName: Funique.UI.ClientUIConfiguration.ShowTimeline
  type: Field
  source:
    remote:
      path: Structure/ClientUIConfiguration.cs
      branch: v1.0
      repo: https://github.com/Funique2022/funique_ui.git
    id: ShowTimeline
    path: ../../../project_unity_development/Assets/FuniquePlugin/UI/Structure/ClientUIConfiguration.cs
    startLine: 16
  assemblies:
  - Funique.UI
  namespace: Funique.UI
  syntax:
    content: >-
      [Header("Base Setting")]

      [Tooltip("The bottom timeline and buttons")]

      [SerializeField]

      public bool ShowTimeline
    return:
      type: System.Boolean
    content.vb: >-
      <Header("Base Setting")>

      <Tooltip("The bottom timeline and buttons")>

      <SerializeField>

      Public ShowTimeline As Boolean
  attributes:
  - type: UnityEngine.HeaderAttribute
    ctor: UnityEngine.HeaderAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: Base Setting
  - type: UnityEngine.TooltipAttribute
    ctor: UnityEngine.TooltipAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: The bottom timeline and buttons
  - type: UnityEngine.SerializeField
    ctor: UnityEngine.SerializeField.#ctor
    arguments: []
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Funique.UI.ClientUIConfiguration.ShowHomeMenu
  commentId: F:Funique.UI.ClientUIConfiguration.ShowHomeMenu
  id: ShowHomeMenu
  parent: Funique.UI.ClientUIConfiguration
  langs:
  - csharp
  - vb
  name: ShowHomeMenu
  nameWithType: ClientUIConfiguration.ShowHomeMenu
  fullName: Funique.UI.ClientUIConfiguration.ShowHomeMenu
  type: Field
  source:
    remote:
      path: Structure/ClientUIConfiguration.cs
      branch: v1.0
      repo: https://github.com/Funique2022/funique_ui.git
    id: ShowHomeMenu
    path: ../../../project_unity_development/Assets/FuniquePlugin/UI/Structure/ClientUIConfiguration.cs
    startLine: 18
  assemblies:
  - Funique.UI
  namespace: Funique.UI
  syntax:
    content: >-
      [Tooltip("The left side of bar")]

      [SerializeField]

      public bool ShowHomeMenu
    return:
      type: System.Boolean
    content.vb: >-
      <Tooltip("The left side of bar")>

      <SerializeField>

      Public ShowHomeMenu As Boolean
  attributes:
  - type: UnityEngine.TooltipAttribute
    ctor: UnityEngine.TooltipAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: The left side of bar
  - type: UnityEngine.SerializeField
    ctor: UnityEngine.SerializeField.#ctor
    arguments: []
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Funique.UI.ClientUIConfiguration.PlayListMenu
  commentId: F:Funique.UI.ClientUIConfiguration.PlayListMenu
  id: PlayListMenu
  parent: Funique.UI.ClientUIConfiguration
  langs:
  - csharp
  - vb
  name: PlayListMenu
  nameWithType: ClientUIConfiguration.PlayListMenu
  fullName: Funique.UI.ClientUIConfiguration.PlayListMenu
  type: Field
  source:
    remote:
      path: Structure/ClientUIConfiguration.cs
      branch: v1.0
      repo: https://github.com/Funique2022/funique_ui.git
    id: PlayListMenu
    path: ../../../project_unity_development/Assets/FuniquePlugin/UI/Structure/ClientUIConfiguration.cs
    startLine: 20
  assemblies:
  - Funique.UI
  namespace: Funique.UI
  syntax:
    content: >-
      [Tooltip("The right side of panel")]

      [SerializeField]

      public bool PlayListMenu
    return:
      type: System.Boolean
    content.vb: >-
      <Tooltip("The right side of panel")>

      <SerializeField>

      Public PlayListMenu As Boolean
  attributes:
  - type: UnityEngine.TooltipAttribute
    ctor: UnityEngine.TooltipAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: The right side of panel
  - type: UnityEngine.SerializeField
    ctor: UnityEngine.SerializeField.#ctor
    arguments: []
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Funique.UI.ClientUIConfiguration.ZoomSlider
  commentId: F:Funique.UI.ClientUIConfiguration.ZoomSlider
  id: ZoomSlider
  parent: Funique.UI.ClientUIConfiguration
  langs:
  - csharp
  - vb
  name: ZoomSlider
  nameWithType: ClientUIConfiguration.ZoomSlider
  fullName: Funique.UI.ClientUIConfiguration.ZoomSlider
  type: Field
  source:
    remote:
      path: Structure/ClientUIConfiguration.cs
      branch: v1.0
      repo: https://github.com/Funique2022/funique_ui.git
    id: ZoomSlider
    path: ../../../project_unity_development/Assets/FuniquePlugin/UI/Structure/ClientUIConfiguration.cs
    startLine: 22
  assemblies:
  - Funique.UI
  namespace: Funique.UI
  syntax:
    content: >-
      [Tooltip("The top right of slider")]

      [SerializeField]

      public bool ZoomSlider
    return:
      type: System.Boolean
    content.vb: >-
      <Tooltip("The top right of slider")>

      <SerializeField>

      Public ZoomSlider As Boolean
  attributes:
  - type: UnityEngine.TooltipAttribute
    ctor: UnityEngine.TooltipAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: The top right of slider
  - type: UnityEngine.SerializeField
    ctor: UnityEngine.SerializeField.#ctor
    arguments: []
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Funique.UI.ClientUIConfiguration.ShowToolbarIcon
  commentId: F:Funique.UI.ClientUIConfiguration.ShowToolbarIcon
  id: ShowToolbarIcon
  parent: Funique.UI.ClientUIConfiguration
  langs:
  - csharp
  - vb
  name: ShowToolbarIcon
  nameWithType: ClientUIConfiguration.ShowToolbarIcon
  fullName: Funique.UI.ClientUIConfiguration.ShowToolbarIcon
  type: Field
  source:
    remote:
      path: Structure/ClientUIConfiguration.cs
      branch: v1.0
      repo: https://github.com/Funique2022/funique_ui.git
    id: ShowToolbarIcon
    path: ../../../project_unity_development/Assets/FuniquePlugin/UI/Structure/ClientUIConfiguration.cs
    startLine: 24
  assemblies:
  - Funique.UI
  namespace: Funique.UI
  syntax:
    content: >-
      [Tooltip("Show the toolbar icon for mobile user")]

      [SerializeField]

      public bool ShowToolbarIcon
    return:
      type: System.Boolean
    content.vb: >-
      <Tooltip("Show the toolbar icon for mobile user")>

      <SerializeField>

      Public ShowToolbarIcon As Boolean
  attributes:
  - type: UnityEngine.TooltipAttribute
    ctor: UnityEngine.TooltipAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: Show the toolbar icon for mobile user
  - type: UnityEngine.SerializeField
    ctor: UnityEngine.SerializeField.#ctor
    arguments: []
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Funique.UI.ClientUIConfiguration.ShortcutUI
  commentId: F:Funique.UI.ClientUIConfiguration.ShortcutUI
  id: ShortcutUI
  parent: Funique.UI.ClientUIConfiguration
  langs:
  - csharp
  - vb
  name: ShortcutUI
  nameWithType: ClientUIConfiguration.ShortcutUI
  fullName: Funique.UI.ClientUIConfiguration.ShortcutUI
  type: Field
  source:
    remote:
      path: Structure/ClientUIConfiguration.cs
      branch: v1.0
      repo: https://github.com/Funique2022/funique_ui.git
    id: ShortcutUI
    path: ../../../project_unity_development/Assets/FuniquePlugin/UI/Structure/ClientUIConfiguration.cs
    startLine: 28
  assemblies:
  - Funique.UI
  namespace: Funique.UI
  syntax:
    content: >-
      [Header("Register")]

      [HideIf("ShowHomeMenu", false)]

      [SerializeField]

      public RectTransform ShortcutUI
    return:
      type: UnityEngine.RectTransform
    content.vb: >-
      <Header("Register")>

      <HideIf("ShowHomeMenu", False)>

      <SerializeField>

      Public ShortcutUI As RectTransform
  attributes:
  - type: UnityEngine.HeaderAttribute
    ctor: UnityEngine.HeaderAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: Register
  - type: Funique.HideIf
    ctor: Funique.HideIf.#ctor(System.String,System.Boolean)
    arguments:
    - type: System.String
      value: ShowHomeMenu
    - type: System.Boolean
      value: false
  - type: UnityEngine.SerializeField
    ctor: UnityEngine.SerializeField.#ctor
    arguments: []
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Funique.UI.ClientUIConfiguration.ShortcutClose
  commentId: F:Funique.UI.ClientUIConfiguration.ShortcutClose
  id: ShortcutClose
  parent: Funique.UI.ClientUIConfiguration
  langs:
  - csharp
  - vb
  name: ShortcutClose
  nameWithType: ClientUIConfiguration.ShortcutClose
  fullName: Funique.UI.ClientUIConfiguration.ShortcutClose
  type: Field
  source:
    remote:
      path: Structure/ClientUIConfiguration.cs
      branch: v1.0
      repo: https://github.com/Funique2022/funique_ui.git
    id: ShortcutClose
    path: ../../../project_unity_development/Assets/FuniquePlugin/UI/Structure/ClientUIConfiguration.cs
    startLine: 30
  assemblies:
  - Funique.UI
  namespace: Funique.UI
  syntax:
    content: >-
      [HideIf("ShowHomeMenu", false)]

      [SerializeField]

      public Button ShortcutClose
    return:
      type: UnityEngine.UI.Button
    content.vb: >-
      <HideIf("ShowHomeMenu", False)>

      <SerializeField>

      Public ShortcutClose As Button
  attributes:
  - type: Funique.HideIf
    ctor: Funique.HideIf.#ctor(System.String,System.Boolean)
    arguments:
    - type: System.String
      value: ShowHomeMenu
    - type: System.Boolean
      value: false
  - type: UnityEngine.SerializeField
    ctor: UnityEngine.SerializeField.#ctor
    arguments: []
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Funique.UI
  commentId: N:Funique.UI
  name: Funique.UI
  nameWithType: Funique.UI
  fullName: Funique.UI
- uid: System.ValueType.Equals(System.Object)
  commentId: M:System.ValueType.Equals(System.Object)
  parent: System.ValueType
  isExternal: true
  name: Equals(Object)
  nameWithType: ValueType.Equals(Object)
  fullName: System.ValueType.Equals(System.Object)
  spec.csharp:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    nameWithType: ValueType.Equals
    fullName: System.ValueType.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    nameWithType: ValueType.Equals
    fullName: System.ValueType.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.ValueType.GetHashCode
  commentId: M:System.ValueType.GetHashCode
  parent: System.ValueType
  isExternal: true
  name: GetHashCode()
  nameWithType: ValueType.GetHashCode()
  fullName: System.ValueType.GetHashCode()
  spec.csharp:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    nameWithType: ValueType.GetHashCode
    fullName: System.ValueType.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    nameWithType: ValueType.GetHashCode
    fullName: System.ValueType.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.ValueType.ToString
  commentId: M:System.ValueType.ToString
  parent: System.ValueType
  isExternal: true
  name: ToString()
  nameWithType: ValueType.ToString()
  fullName: System.ValueType.ToString()
  spec.csharp:
  - uid: System.ValueType.ToString
    name: ToString
    nameWithType: ValueType.ToString
    fullName: System.ValueType.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.ValueType.ToString
    name: ToString
    nameWithType: ValueType.ToString
    fullName: System.ValueType.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.ValueType
  commentId: T:System.ValueType
  parent: System
  isExternal: true
  name: ValueType
  nameWithType: ValueType
  fullName: System.ValueType
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: UnityEngine.RectTransform
  commentId: T:UnityEngine.RectTransform
  parent: UnityEngine
  isExternal: true
  name: RectTransform
  nameWithType: RectTransform
  fullName: UnityEngine.RectTransform
- uid: UnityEngine
  commentId: N:UnityEngine
  isExternal: true
  name: UnityEngine
  nameWithType: UnityEngine
  fullName: UnityEngine
- uid: UnityEngine.UI.Button
  commentId: T:UnityEngine.UI.Button
  parent: UnityEngine.UI
  isExternal: true
  name: Button
  nameWithType: Button
  fullName: UnityEngine.UI.Button
- uid: UnityEngine.UI
  commentId: N:UnityEngine.UI
  isExternal: true
  name: UnityEngine.UI
  nameWithType: UnityEngine.UI
  fullName: UnityEngine.UI
