### YamlMime:ManagedReference
items:
- uid: Funique.Cinema.MapStereoConfig
  commentId: T:Funique.Cinema.MapStereoConfig
  id: MapStereoConfig
  parent: Funique.Cinema
  children:
  - Funique.Cinema.MapStereoConfig.Mode
  - Funique.Cinema.MapStereoConfig.Target
  langs:
  - csharp
  - vb
  name: MapStereoConfig
  nameWithType: MapStereoConfig
  fullName: Funique.Cinema.MapStereoConfig
  type: Struct
  source:
    remote:
      path: Struct/MapStereoConfig.cs
      branch: v1.0
      repo: https://github.com/Funique2022/funique_cinema.git
    id: MapStereoConfig
    path: ../../../project_unity_development/Assets/FuniquePlugin/Cinema/Struct/MapStereoConfig.cs
    startLine: 7
  assemblies:
  - Funique.Cinema
  namespace: Funique.Cinema
  summary: "\nVideo packing mode config <br />\n------------------------------------------------ <br />\n影像切片模式配置\n"
  example: []
  syntax:
    content: >-
      [Serializable]

      public struct MapStereoConfig
    content.vb: >-
      <Serializable>

      Public Structure MapStereoConfig
  inheritedMembers:
  - System.ValueType.Equals(System.Object)
  - System.ValueType.GetHashCode
  - System.ValueType.ToString
  attributes:
  - type: System.SerializableAttribute
    ctor: System.SerializableAttribute.#ctor
    arguments: []
  modifiers.csharp:
  - public
  - struct
  modifiers.vb:
  - Public
  - Structure
- uid: Funique.Cinema.MapStereoConfig.Mode
  commentId: F:Funique.Cinema.MapStereoConfig.Mode
  id: Mode
  parent: Funique.Cinema.MapStereoConfig
  langs:
  - csharp
  - vb
  name: Mode
  nameWithType: MapStereoConfig.Mode
  fullName: Funique.Cinema.MapStereoConfig.Mode
  type: Field
  source:
    remote:
      path: Struct/MapStereoConfig.cs
      branch: v1.0
      repo: https://github.com/Funique2022/funique_cinema.git
    id: Mode
    path: ../../../project_unity_development/Assets/FuniquePlugin/Cinema/Struct/MapStereoConfig.cs
    startLine: 15
  assemblies:
  - Funique.Cinema
  namespace: Funique.Cinema
  summary: "\nStereo mode \n------------------------------------------------ <br />\n影像切片模式\n"
  example: []
  syntax:
    content: public StereoMode Mode
    return:
      type: Funique.StereoMode
    content.vb: Public Mode As StereoMode
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Funique.Cinema.MapStereoConfig.Target
  commentId: F:Funique.Cinema.MapStereoConfig.Target
  id: Target
  parent: Funique.Cinema.MapStereoConfig
  langs:
  - csharp
  - vb
  name: Target
  nameWithType: MapStereoConfig.Target
  fullName: Funique.Cinema.MapStereoConfig.Target
  type: Field
  source:
    remote:
      path: Struct/MapStereoConfig.cs
      branch: v1.0
      repo: https://github.com/Funique2022/funique_cinema.git
    id: Target
    path: ../../../project_unity_development/Assets/FuniquePlugin/Cinema/Struct/MapStereoConfig.cs
    startLine: 21
  assemblies:
  - Funique.Cinema
  namespace: Funique.Cinema
  summary: "\nModify scene data config\n------------------------------------------------ <br />\n變更資料配置\n"
  example: []
  syntax:
    content: public StereoConfig Target
    return:
      type: Funique.Cinema.StereoConfig
    content.vb: Public Target As StereoConfig
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Funique.Cinema
  commentId: N:Funique.Cinema
  name: Funique.Cinema
  nameWithType: Funique.Cinema
  fullName: Funique.Cinema
- uid: System.ValueType.Equals(System.Object)
  commentId: M:System.ValueType.Equals(System.Object)
  parent: System.ValueType
  isExternal: true
  name: Equals(Object)
  nameWithType: ValueType.Equals(Object)
  fullName: System.ValueType.Equals(System.Object)
  spec.csharp:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    nameWithType: ValueType.Equals
    fullName: System.ValueType.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    nameWithType: ValueType.Equals
    fullName: System.ValueType.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.ValueType.GetHashCode
  commentId: M:System.ValueType.GetHashCode
  parent: System.ValueType
  isExternal: true
  name: GetHashCode()
  nameWithType: ValueType.GetHashCode()
  fullName: System.ValueType.GetHashCode()
  spec.csharp:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    nameWithType: ValueType.GetHashCode
    fullName: System.ValueType.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    nameWithType: ValueType.GetHashCode
    fullName: System.ValueType.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.ValueType.ToString
  commentId: M:System.ValueType.ToString
  parent: System.ValueType
  isExternal: true
  name: ToString()
  nameWithType: ValueType.ToString()
  fullName: System.ValueType.ToString()
  spec.csharp:
  - uid: System.ValueType.ToString
    name: ToString
    nameWithType: ValueType.ToString
    fullName: System.ValueType.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.ValueType.ToString
    name: ToString
    nameWithType: ValueType.ToString
    fullName: System.ValueType.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.ValueType
  commentId: T:System.ValueType
  parent: System
  isExternal: true
  name: ValueType
  nameWithType: ValueType
  fullName: System.ValueType
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Funique.StereoMode
  commentId: T:Funique.StereoMode
  parent: Funique
  name: StereoMode
  nameWithType: StereoMode
  fullName: Funique.StereoMode
- uid: Funique
  commentId: N:Funique
  name: Funique
  nameWithType: Funique
  fullName: Funique
- uid: Funique.Cinema.StereoConfig
  commentId: T:Funique.Cinema.StereoConfig
  parent: Funique.Cinema
  name: StereoConfig
  nameWithType: StereoConfig
  fullName: Funique.Cinema.StereoConfig
