# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "docfx" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      #- name: Folder structure
        #run: cd / && mkdir app && cd app
        
      - uses: actions/checkout@v3
        name: Clone docfx git
          
      - uses: nikeee/docfx-action@v1.0.0
        name: Build docfx files
        with:
          args: docfx.json
          
      - uses: actions/checkout@v3
        name: Switch web branch
        with:
          ref: web
          path: web
          repository: Funique2022/.github
          token: ${{ secrets.ACCESS_TOKEN }}
          ssh-key: ${{ secrets.SSH_KEY }}
      
      - name: Copy all files to web branch
        run: cp -rf ../static/* ../static
        
      - uses: stefanzweifel/git-auto-commit-action@v4
        name: Commit update
      
      - name: Upload to docker center
        run: ls
