# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "docfx" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      #- name: Folder structure
        #run: cd / && mkdir app && cd app
        
      - uses: actions/checkout@v2
        name: Clone docfx git
          
      - uses: actions/checkout@v2
        name: Switch web branch
        with:
          ref: web
          path: web
          repository: Funique2022/.github
          token: ${{ secrets.ACCESS_TOKEN }}
      
      - uses: nikeee/docfx-action@v1.0.0
        name: Build docfx files
        with:
          args: docfx_ci.json
      
      - name: Copy all files to web branch
        run: cp -rf ../static/* web/static
      
      - uses: EndBug/add-and-commit@v9
        name: Add changes
      
      - uses: actions-js/push@master
        name: Push changes
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          branch: web
      
      - name: Upload to docker center
        run: ls
